### ISSUE TITLE
выделение социальных кнопок на странице с китом в отдельный блок

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#10]
Сейчас соц кнопки находятся внутри блока с описанием страны, нужно их выделить в отдельный блок, что-бы их можно было легко перемещать. Например поставить после блока best time to visit.

**Comment by SilentImp** [comment]
Это уже отдельный блок, который можно перемещать:

```
.social-likes.social-likes_both.social-likes_alone
  .facebook(title="Share link on Facebook") Share
  .twitter(title="Share link on Twitter",  data-via="vacaykit") Tweet
  .pinterest(title="Share image on Pinterest", data-media="images/header_bg_5.jpg") Pin
```

Добавил класс для использования под блоком `best time to visit` и демо.
