### ISSUE TITLE
ресайз картинок для путеводителей

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#12]
см http://vacaykit.com/asia/thailand/

Картинка последнего гида растянута по ширине. Картинки должны быть фиксированной высоты, но не ширины.

**Comment by SilentImp** [comment]
Сейчас там используется `background-size: cover;` — картинка ресайзится так, что бы полностью покрывать блок, пропорции не искажаются. Изменил на `background-size: auto 100%;` — теперь картинка всегда по высоте равна блоку, а по ширине — с сохранением пропорций, может не закрывать блок полностью.
