### ISSUE TITLE
отступ от обновленного футера

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#14]
отступ от футера должен остаться таким как был. дисклеймер не должен перекрывать меню с активити

![screen shot 2015-07-13 at 01 18 15](https://cloud.githubusercontent.com/assets/61111/8640559/5a5550de-28fd-11e5-98c8-bb6323813846.png)
![screen shot 2015-07-13 at 01 18 29](https://cloud.githubusercontent.com/assets/61111/8640561/5e850f96-28fd-11e5-820d-5e8078a5c716.png)

![screen shot 2015-07-13 at 01 19 34](https://cloud.githubusercontent.com/assets/61111/8640563/6373da32-28fd-11e5-97a9-cdc06168858e.png)

**Comment by SilentImp** [comment]
Первое — поправил. 
Второе — изначально было поправлено. Думаю у вас скрипт кешировался, сбросьте кеш и должно быть ок.
