### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#15]
посмотри что ты можешь сделать из этого: 

![screen shot 2015-07-14 at 12 30 52](https://cloud.githubusercontent.com/assets/61111/8671306/51c0930c-2a24-11e5-9102-3738c62cb194.png)

**Comment by antonreshetnikov** [comment]
Если что-то из этого требует изменения настроек сервера, дай мне знать

**Comment by antonreshetnikov** [comment]
Выше был репорт о главной странице. 
Вот еще  дополнительно про страницу с китом: 

![screen shot 2015-07-14 at 12 48 42](https://cloud.githubusercontent.com/assets/61111/8671597/c99a1496-2a26-11e5-91dd-ce1dd9234fb9.png)

**Comment by SilentImp** [comment]
1. отключить блокирующий css и js до контента — он намеренно блокирующий. Без него нечего показывать и ничего не будет работать. Сейчас посмотрю — что то можно перенесети в конец, думаю. 
2. заголовки кеширования — это уже задача по настройке сервера/бекенду. 
3. Модернизр и handlebars сейчас ужму

**Comment by SilentImp** [comment]
Пересобрал. 
Проверьте что вышло.
