### ISSUE TITLE
исправления в верстке для SEO

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#17]
См мой комментарий. Эту задачу я частично выполнил сам. 

Нужно везде убрать h1 из логотипа. 

<h3>для всех страниц:</h3>

убрать h1 из лого:

```
<a href="/">
          <h1 class="logotype">Vacaykit</h1></a>
```

убрать h2 из верхнего меню с выпадающим списком: 

```
          <div class="dropdown">
            <h2 class="dropdown__title">Popular Lists</h2>
```

<h3>для главной страницы:</h3>

нужно добавить h1 перед p.landing__mesage и текст самого landing message разделить на две части. Первое предложение идет в h1, а остальное в p.landing__mesage:

```
 <section class="landing">
     <h1>VacayKit is a simple online app designed to deliver customized travel kits for unique holiday activities anywhere you want to go in the world.</h1>
    <p class="landing__message"> Pick your destination, grab your vacation kits, and have the holiday experience of a lifetime!</p>
```

отображаться все это должно также как и раньше

<h3>для страницы со страной и других контент страниц:</h3>

сейчас так:

```
 <h2 class="kit kit_malaysia">
     <span class="kit__region">Asia</span>
    <span class="kit__country">Malaysia</span>
    <span class="kit__count">10 activities</span>
</h2>
```

нужно сделать так что-бы регион был не в h2, а название страны должно быть в h1, то есть что-то типа этого:

```
 <span class="kit kit_malaysia">
    <span class="kit__region">Asia</span>
   <h1 class="kit__country">Malaysia</h1>
   <span class="kit__count">10 activities</span>
</span>
```

**Comment by antonreshetnikov** [comment]
Я сам внес эти изменения (см  мой коммит от Jul 18, 2015). Issue не закрываю так как хочу что-бы ты посмотрел что все ок.

Так же исправь пожалуйста, что-бы на главной в <div class="landing__message">  на разрывалась строка между H1 и P.

**Comment by SilentImp** [comment]
Не нашел H1 на главной. 
Это же http://vacaykit.com/ или home.html верно?

**Comment by antonreshetnikov** [comment]
Я сам внес эти изменения (см мой коммит от Jul 18, 2015).

**Comment by antonreshetnikov** [comment]
Смотри код страницы vacaykit.com:

```
  <div class="landing__message"> 
        <h1>VacayKit is a simple online app designed to deliver customized packing lists for unique holiday activities anywhere you want to go.</h1>
        <p>Pick your destination, grab your vacation kits, and have the holiday experience of a lifetime!</p>
      </div>
```

В   home.html сейчас есть  

```
<a href="/"><h1 class="logotype">VacayKit</h1></a>
```

а должно быть 

```
 <a href="/"><div class="logotype">VacayKit</div></a>
```

Внеси пожалуйста эти изменения в репозиторий

**Comment by antonreshetnikov** [comment]
Это уже было так давно, что я забыл что сам уже все сделал. issue закрываю
