### ISSUE TITLE
отправление письма со страницы vacaykit.com/contact 

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#18]
Нужно найти решение  (провайдера API) которое бы предоставляло возможность инициировать отправку письма из формы фидбэка на стороне клиента. 

Нужно найти подходящего провайдера API и настроить все.

**Comment by SilentImp** [comment]
Я использовал сервис MailChimp https://mandrillapp.com/
Проверил — работает. 
Вам нужно заменить в contacts.coffee 

```
"email": "ravenb@mail.ru",
"name": "Anton Nemtsev",
"subject": "Message from VacayKit contact us form",
```

На желаемые и зарегистрировать свой ключ

```
"key": "aG3qodBxJFzJhMPyO1y_EQ",
```
