### ISSUE TITLE
работа меню с активитис на странице с китом в мобильной версии

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#2]
На странице с китом в мобильной версии если прокрутить страницу примерно до пятого кита (до того момента когда верхнее меню должно проскролиться) и продолжить крутить дальше меню с активитис начинает подергиваться взад-вперед

**Comment by SilentImp** [comment]
Больше не дергается, но я обнаружил баг с прокруткой к нужному элементу на мобильном. 
Создаю еще одно issue по этому поводу
