### ISSUE TITLE
редизайн социальных кнопок

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#23]
Переделать дизайн социальных кнопок в соответсвии с макетом vacaykit_v5_soc_buttons.sketch (в расшареной папке dropbox)

<img width="1111" alt="screen shot 2015-09-16 at 18 30 05" src="https://cloud.githubusercontent.com/assets/61111/9911180/29537254-5ca1-11e5-9a15-828f9515f6fe.png">

<img width="330" alt="screen shot 2015-09-16 at 18 30 14" src="https://cloud.githubusercontent.com/assets/61111/9911182/2c91551c-5ca1-11e5-8ae0-fc01149bf010.png">

**Comment by SilentImp** [comment]
Я у себя не вижу как оно с цифрами выглядит.
Проверь пожалуйста все ли ок.

**Comment by antonreshetnikov** [comment]
http://vacaykit.com/packing-list/sri-lanka/

выглядит не совсем так как на макете: 
- нужно убрать надписи
- добравить g+
- в мобильном варианте оно должно уменьшаться что-бы 4 иконки умещались в ширину экрана

**Comment by antonreshetnikov** [comment]
сейчас выгдядит так:

<img width="908" alt="screen shot 2015-09-16 at 21 56 24" src="https://cloud.githubusercontent.com/assets/61111/9916676/dcd314f8-5cbd-11e5-8344-0c5313865734.png">

**Comment by antonreshetnikov** [comment]
в предыдущий комментарии я недогрузил все что нужно. 
Вот как это выглядит живьем:
http://vacaykit.com/packing-list/sri-lanka/

выглядит не совсем так как на макете (вверху sketch, внизу chrome): 

<img width="518" alt="screen shot 2015-09-16 at 22 28 03" src="https://cloud.githubusercontent.com/assets/61111/9917505/436d3e60-5cc2-11e5-8885-74e7971b84f3.png">
- нет версии для маленького экрана

**Comment by antonreshetnikov** [comment]
Вот пример страницы где цифры побольше: 
http://vacaykit.com/blog/10-things-you-should-know-before-traveling-to-southeast-asia/

**Comment by antonreshetnikov** [comment]
Небольшое обновление: 

Предлагаю если в кнопке нет цифры, то показывать там надпись, а если есть лайк то показывать соответсвенно количество лайков:

<img width="825" alt="screen shot 2015-09-17 at 11 46 14" src="https://cloud.githubusercontent.com/assets/61111/9930172/379ec174-5d32-11e5-9c87-d828a2815a30.png">

Если нужно могу загрузить новый макет. Это возможно?

**Comment by SilentImp** [comment]
Я посмотрю, но вряд ли. 
Для этого скорее всего придется вносить правки в библиотеку

**Comment by antonreshetnikov** [comment]
Давай в начале, посмотрим как будет выглядеть версия из макета.

**Comment by SilentImp** [comment]
Выложил. 
Пожалуйста проверьте.

**Comment by antonreshetnikov** [comment]
Задеплоил вот сюда:  http://vacaykit.com/packing-list/sri-lanka/ 

все работает отлично, единсвенный момент это то что а десктопной версии иконки и шрифты меньше чем в макете.

См скриншот: вверху sketch, внизу - chrome  

<img width="523" alt="screen shot 2015-09-19 at 16 58 54" src="https://cloud.githubusercontent.com/assets/61111/9976811/dff2f93a-5eef-11e5-95c3-de67c3a6ecd4.png">

Исправь пожалуйста и можно закрывать эту issue. Спасибо!

**Comment by SilentImp** [comment]
Проверь

**Comment by antonreshetnikov** [comment]
Все отлично, спасибо!
