### ISSUE TITLE
добавить пару иконок соц сетей

### ISSUE THREAD

**Issue by antonreshetnikov** [antonreshetnikov/VacayKit#4]
Добавить иконку инстаграма в футер и иконку linkedin для станицы about (соц сети участников команды)

**Comment by SilentImp** [comment]
Адреса, на которые они должны вести уточните, пожалуйста.

**Comment by antonreshetnikov** [comment]
Ссылки я могу потом без проблем добавить, важно чтобы ты отбавил соответсвующие иконки в /images и в верстку 

Инстаграм в футер: Instagram.com/vacaykit 

Ссылку на Linked in сделай пока пустой так как я не могу сейчас дать тебе точный линк

Спасибо.

Антон
